INSERT INTO events_subtypes (event_id, subtype_id) VALUES (1, 1);
INSERT INTO events_subtypes (event_id, subtype_id) VALUES (1, 2);
INSERT INTO events_subtypes (event_id, subtype_id) VALUES (1, 3);
INSERT INTO events_subtypes (event_id, subtype_id) VALUES (2, 1);
INSERT INTO events_subtypes (event_id, subtype_id) VALUES (2, 2);
INSERT INTO events_subtypes (event_id, subtype_id) VALUES (2, 3);
INSERT INTO events_subtypes (event_id, subtype_id) VALUES (2, 4);
INSERT INTO events_subtypes (event_id, subtype_id) VALUES (3, 1);
INSERT INTO events_subtypes (event_id, subtype_id) VALUES (4, 1);